name: Deploy to QA

on:
  push:
    branches: [ develop ]

jobs:
  mutation-baseline:
    name: Update mutation score baseline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install stryker
        run: |
          dotnet tool install --global dotnet-stryker

      - name: Install dependencies
        run: |
          dotnet restore      

      - name: Run mutation testing
        run: |
          git fetch origin ${{github.base_ref}}
          pushd ./test/Playground.Core.Tests
          dotnet stryker --baseline-storage-location=Dashboard --dashboard-api-key=${{ secrets.STRYKER_DASHBOARD_API_KEY }} --dashboard-project="github.com/${{ github.repository }}" --dashboard-version=${{ github.head_ref }}
          popd