name: Mutation score baseline

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  mutation-baseline:
    name: Update mutation score baseline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install stryker
        run: |
          dotnet tool install --global dotnet-stryker

      - name: Install dependencies
        run: |
          dotnet restore

      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Run mutation testing
        run: |
          pushd ./test/Playground.Core.Tests
          dotnet stryker --dashboard-api-key=${{ secrets.STRYKER_DASHBOARD_API_KEY }} --dashboard-project="github.com/${{ github.repository }}" --dashboard-version=${{ steps.vars.outputs.short_ref }}
          popd
